# Generated by Django 4.1.7 on 2023-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('posterimage', models.ImageField(upload_to='movie')),
            ],
        ),
    ]
